### ISSUE TITLE
Containerize : generate app-dev.yml

### ISSUE THREAD

**Issue by pascalgrimaud** [pascalgrimaud/generator-jhipster-docker#18]
Related to https://github.com/jhipster/generator-jhipster/issues/2607

A new file app-dev.yml should be generated too : it will be easier to test the app inside a container in dev profile

**Comment by gmarziou** [comment]
@pascalgrimaud  I don't see clearly the link with #2607, is it the right number?

Unless you wanted to set server.contextPath in app-dev.yml

**Comment by pascalgrimaud** [comment]
The 3rd option of this module containerize a JHipster application, with Tomcat or JBoss Wildfly.
But, the generated app.yml start the Tomcat or JBoss in production profile only.

When I wanted to test jhipster/generator-jhipster#2607, I had to write manually the `app-dev.yml` to start container in development profile => so I should generate a `app-dev.yml` too, to start the Tomcat or JBoss in development profile

It's because swagger is available only in dev profile.

I don't know if I'm clear enough ?

**Comment by gmarziou** [comment]
Very clear, thanks.

**Comment by pascalgrimaud** [comment]
already done in the main core generator-jhipster -> simply put SPRING_PROFILES_ACTIVE=dev to docker-compose file
