### ISSUE TITLE
mvnw: Permission denied

### ISSUE THREAD

**Issue by SzymonWiniarz** [pascalgrimaud/generator-jhipster-docker#29]
I'm setting new, fresh application with jhipster generator, then I'm generating Dockerfile with jhipster-docker generator, setting git repo, creating Automated Build on Docker HUB, everything as described in the readme of the generator-jhipster-docker.
Unfortunatelly, when I push my changes to the remote repo, the build on Docker HUB fails with folllwing output:
` ---> Running in 2dfba8210237
 [91m/bin/sh: 1: ./mvnw: Permission denied
 [0m Removing intermediate container 2dfba8210237 The command '/bin/sh -c echo '{ "allow_root": true }' > /root/.bowerrc && cd /code/ && ./mvnw clean package -Pprod -DskipTests && mv /code/target/*.war /app.war && rm -Rf /code /root/.npm/ /tmp && rm -Rf /root/.m2/' returned a non-zero code: 126`

I'm using Bitbucket not the GitHub, for my project but I think this should not be the problem (at least not at this point).

Versions of the generators I'm using:
jhipster: 3.12.2
jhipster-docker: 2.2.0

**Comment by PierreBesson** [comment]
Does doing a `chmod +x mvnw` then committing your change fixes the problem ?

**Comment by SzymonWiniarz** [comment]
Thank you for your response.
Adding this command to the generated Docker file, just after _cd /code/_ command, solved the problem.
One more thing I noticed is that such build on Docker HUB takes extremally lot of time now (about 15 minutes) and it's probably caused by the fact, that ./mvnw everytime, on every build, is downloading all dependencies needed by the project. But this is rather field for improvements, not a bug itself.

**Comment by PierreBesson** [comment]
@SzymonWiniarz Docker Hub is not especially optimized for maven/npm projects.
If you were using Jenkins, Travis or other CI systems for you docker builds, you will be able to benefit from maven and npm/yarn caches.

**Comment by PierreBesson** [comment]
@pascalgrimaud you can close this issue.

**Comment by SzymonWiniarz** [comment]
Ok, thank you for your advice.

**Comment by pascalgrimaud** [comment]
@SzymonWiniarz :
- I know that Docker Hub is too long to build. As suggested by Pierre, you can use Travis or another CI to push your image after a build, but you will lost the "Automated Build"
- for the chmod +x on maven wrapper, I will propably adding it to the current Dockerfile, but it's strange that bitbucket should keep all permissions unless you didnt push it with +x

@PierreBesson thanks for answers ;-)

**Comment by bagulm123** [comment]
> Does doing a `chmod +x mvnw` then committing your change fixes the problem ?

Dont forget to add && at the end of it (because this will become like  **chmod +x mvnw ./mvnw clean package -Pprod**  and error will be like **chmod: invalid option -- 'P'** if you dont add &&

**Comment by pfrumau** [comment]
> Does doing a `chmod +x mvnw` then committing your change fixes the problem ?

command = git update-index --chmod=+x mvnw
then push changes.

fixed issues for me

**Comment by Nishantbarh** [comment]
running "chmod +x mvnw" in cloned directory solved this issue with maven wrapper build.

**Comment by ikomangmahendra** [comment]
> > Does doing a `chmod +x mvnw` then committing your change fixes the problem ?
> 
> command = git update-index --chmod=+x mvnw then push changes.
> 
> fixed issues for me

Thanks, this is the best solution

**Comment by anilpatil46** [comment]
Or  ....After git clone to local on Jenkins workspace next command you can add in script is chmod +x mvnw  , this helped me.
